### PR TITLE
Fix | added check on noteTitle's url patch

### LINKED ISSUE #309: [Bug]: Note settings tab patches to note name
Sometimes we can see, that note settings tab patches just to note title 

Image

Need to find a bug, probably in openedPages storage

### PR DESCRIPTION
**Pull request by TheGeniusOfEternity**
Added check to prevent Note Settings page patch. This resolves #309

### CODE REVIEW

File: src/application/services/useNote.ts [hunk 1]
```diff
@@ -322,12 +322,16 @@ export default function (options: UseNoteComposableOptions): UseNoteComposableSt
...
+    const routes = ['/settings', '/history', '/error'];
+
+    if (routes.every(rt => !route.path.includes(rt))) {
+      patchOpenedPageByUrl(
+        route.path,
+        {
+          title: currentNoteTitle,
+          url: route.path,
+        });
+    }
```
Comment (e11sy) [inline src/application/services/useNote.ts:334]: maybe we can just check for regex match?
it should match the `/note\/*{10}/` where 10 is length of the noteId

then we know that route is related to the note

File: src/application/services/useNote.ts [hunk 2]
```diff
@@ -322,12 +322,14 @@ export default function (options: UseNoteComposableOptions): UseNoteComposableSt
   });
 
   watch(noteTitle, (currentNoteTitle) => {
-    patchOpenedPageByUrl(
-      route.path,
-      {
-        title: currentNoteTitle,
-        url: route.path,
-      });
+    if (!route.path.match('/note/.{10}/')) {
```
Comment (e11sy) [inline src/application/services/useNote.ts:325]: now it seems very strange, we patch all the titles that are not related to the note actually?

Comment (TheGeniusOfEternity) [reply src/application/services/useNote.ts:325]: Yeah, like before changes. Now we just don't patch url if route path contains only note's url

**Review by e11sy — APPROVED** [review]

File: src/application/services/useNote.ts [hunk 3]
```diff
@@ -379,13 +379,14 @@ export default function (options: UseNoteComposableOptions): UseNoteComposableSt
...
 
   watch(noteTitle, (currentNoteTitle) => {
-    patchOpenedPageByUrl(
-      route.path,
-      {
-        title: currentNoteTitle,
-        url: route.path,
-      });
-
+    if (!route.path.match('/note/.{10}/')) {
```
Comment (neSpecc) [inline src/application/services/useNote.ts:382]: why not use `route.name`?

Comment (TheGeniusOfEternity) [reply src/application/services/useNote.ts:382]: Hmm, yeah, it would be better, will replace!

**Review by neSpecc — APPROVED** [review]
